### ISSUE TITLE
Random Sort

### ISSUE THREAD

**Issue by gorirrajoe** [pixlee/pixlee-php-v1#3]
Hi - How do I sort the objects randomly (instead of "recent")

```
  $pixlee = new Pixlee( $apiKey, $secretKey, $userID );

  $photos = $pixlee->getPhotos( $albumid, array(
    'sort' => 'recent',
    'per_page' => 16
  ) );
```

**Comment by jchen123** [comment]
'sort' => 'random' should work.

**Comment by gorirrajoe** [comment]
i thought so too, but i get an error:

Fatal error: Uncaught exception 'Exception' with message '404 - Not found ' in C:\xampp\htdocs\rnr\wp-content\themes\rnr3\pixlee\Pixlee.php:115 Stack trace: #0 C:\xampp\htdocs\rnr\wp-content\themes\rnr3\pixlee\Pixlee.php(66): Pixlee->handleResponse('{"status":404,"...', Resource id #156) #1 C:\xampp\htdocs\rnr\wp-content\themes\rnr3\pixlee\Pixlee.php(23): Pixlee->getFromAPI('/albums/162836', Array) #2 C:\xampp\htdocs\rnr\wp-content\themes\rnr3\pixlee\api.php(18): Pixlee->getPhotos('162836', Array) #3 {main} thrown in C:\xampp\htdocs\rnr\wp-content\themes\rnr3\pixlee\Pixlee.php on line 115

**Comment by jchen123** [comment]
My apologies.  Upon further review, unfortunately the random capability is not available for this version of the library.

The updated API can be viewed here: http://docs.pixleeapi.apiary.io/# which has functionality for filters and sorts, including random.

**Comment by gorirrajoe** [comment]
ah! thanks.
is there an update for pixlee (php) using the v2 api coming soon?

**Comment by jchen123** [comment]
Unfortunately we don't have an exact timeline there.  Generally most or all of our implementations have used the REST API.

**Comment by gorirrajoe** [comment]
ok i updated to v2 and got it to grab the objects, but the sorting isn't working properly -- can you possibly push me in the right direction? the result is the same whether i add the sort or not

```
  $json_sort = '[
    { "random" : true },
    {"asc" : true }
  ]';
  $sort = json_decode( $json_sort );

  $photos = $pixlee->getPhotos( $albumid, array(
    'sort' => $sort,
    'per_page' => 16
  ) );
  echo json_encode( $photos );

```

**Comment by jchen123** [comment]
Joe, is the endpoint you're hitting a distillery.pixlee.com endpoint? api.pixlee.com leads to the v1 and is incorrect.

**Comment by gorirrajoe** [comment]
the endpoint is distillery.pixlee.com -- i modified awad's code. did you want me to add the code here?

**Comment by jchen123** [comment]
Could you copy paste the distillery.pixlee.com url it is generating
(redacting the API key)?

- jzc

**Comment by gorirrajoe** [comment]
https:\/\/distillery.pixlee.com\/api\/v2\/albums\/162836\/photos?api_key=[REDACTED]&sort%5B0
%5D%5Brandom%5D=1&sort%5B1%5D%5Basc%5D=1&per_page=16

**Comment by gorirrajoe** [comment]
did some playing around and changed the `$json_sort` variable:

```
  $pixlee = new Pixlee( $apiKey, $secretKey, $userID );
  $json_sort = '{"random":true}';
  // $sort = json_decode( $json_sort );

  $photos = $pixlee->getPhotos( $albumid, array(
    'sort' => $json_sort,
    'per_page' => 16
  ) );
  echo json_encode( $photos );
```

url generated: https:\/\/distillery.pixlee.com\/api\/v2\/albums\/162836\/photos?api_key=[]REDACTED&sort=%7B
%22random%22%3Atrue%7D&per_page=16

this looks like it's working, but when i refresh the page, it doesn't re-arrange the objects randomly

**Comment by jchen123** [comment]
Ah - my apologies.  Looks like there's a bit of the documentation missing.  If you add a unique_id parameter to the end of that url, it will serve as the random seed.  i.e. &unique_id=43234.  Can use a unix timestamp here to consistently break cache.

**Comment by gorirrajoe** [comment]
looks like the php time() function doesn't work as well, the number may be too high?
i'm just going to use a rand(1, 100) for now... i think that should suffice for us

**Comment by jchen123** [comment]
That totally works as well.

**Comment by gorirrajoe** [comment]
THANK YOU SO MUCH FOR YOUR HELP!

**Comment by jchen123** [comment]
Not a problem.  Can also just email me at jeff@pixleeteam.com
